### ISSUE TITLE
No Constructor found for widget on hybrid

### ISSUE THREAD

**Issue by simo101** [mendix/HTMLSnippet#1] opened 2015-02-05 12:05 UTC
I get the following error when trying to use the html snippet on the hybrid mobile app:

No constructor found for widget
HTMLSnippet.widget.HTMLSnippet

Not sure what the issue is but it seems to be 5.13 issue as I had it working in 5.12 before.

**Comment by RoelandSalij** [comment] 2015-02-10 10:56
Issue which is caused by 5.13 and fixed in 5.13.1

**Closed** 2015-02-10 10:56 UTC
Labels: invalid
